### ISSUE TITLE
Определить модель БД

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/HR_in_pocket#2]
Требуется описать структуру БД:
- Набор сущностей с их свойствами
- Связи между сущностями
- Ограничения

**Comment by Infarh** [comment]
На данный момент представляется следующая структура:

- Пользователь
- Роль
- Соискатель
- Исполнитель
- Резюме

**Comment by Infarh** [comment]
- Тарифный план

**Comment by MrAliev** [comment]
Комит по ссылке https://github.com/OpenGeekBrains/HR_in_pocket/commit/ea195478a0ccff9f8178c09ec332b808b304335d

**Comment by Evreinov** [comment]
Может в BaseEntity добавить такие свойства, как:
Кластерный ключ Id - auto increment для оптимизации хранения (потому что guid не упорядочен, а целочисленный тип упорядочен), а текущий Guid, использовать как первичный ключ (потому, как я понимаю будет распределенная БД).
Дата создания объекта.
Дата последнего редактирования объекта.

Кстати, как файлы хранить будем? В виде блобов?

**Comment by MrAliev** [comment]
Резюме (по-мимо файлов) надо ещё будет хранить в распарсенном виде. Нам надо будет ходить по всяким hh.ru и стягивать оттуда инфу по вакансиям/резюме через их внешние api.

**Comment by MrAliev** [comment]
Жду ревью #15
