### ISSUE TITLE
Сущность Тарифный план

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/HR_in_pocket#22]
Отношение с Соискателем - один-ко-многим: один тарифный план может быть у множества соискателей. У соискателя может быть 0, или 1 выбранный им тарифный план.

Свойства:
- Название (string)
- Цена (decimal(18,2))
- Описание (string)

**Comment by MrAliev** [comment]
https://github.com/OpenGeekBrains/HR_in_pocket/pull/38
