### ISSUE TITLE
Интерфейс ВЕБ-приложения

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/HR_in_pocket#3]
Сформировать макет и подготовить разметку для следующих представлений

- [x] Главная страница
- [ ] Форма регистрации/входа
- [ ] Профиль соискателя

**Comment by Yana2403** [comment]
[HR.zip](https://github.com/OpenGeekBrains/HR_in_pocket/files/5503124/HR.zip)

**Comment by Infarh** [comment]
Доработанная версия разметки
[HR.zip](https://github.com/OpenGeekBrains/HR_in_pocket/files/5506945/HR.zip)

**Comment by Yana2403** [comment]
[HR.zip](https://github.com/OpenGeekBrains/HR_in_pocket/files/5509417/HR.zip)
Добавлено: страница создания задания
Исправлено: отображение элемента в секции "как это работает" на главной странице, корректировка цены в тарифе

**Comment by Yana2403** [comment]
[HR.zip](https://github.com/OpenGeekBrains/HR_in_pocket/files/5518419/HR.zip)
Исправление картинки и  формы на главной странице
