### ISSUE TITLE
Прототип механизма разбора html-страницы источника данных по вакансиям

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/HR_in_pocket#50]
- Написать консольное/wpf приложение, осуществляющее скачивание страницы источника данных и выполняющее извлечение данных по средствам библиотек AngleSharp/HtmlAgilityPack.

Данные вывести на экран в табличной форме и сохранить в xml/json файл. Имя файла - название сайта + время доступа к нему.

netstandard2.0

**Comment by mnocard** [comment]
https://github.com/OpenGeekBrains/HR_in_pocket/blob/WPFApp/src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
Здесь тестовый парсер открывает страницу асинхронно, Павел говорил, что асинхронности вроде стоит избегать, чтобы не словить бан.

**Comment by Dmitry-Ischenko** [comment]
> https://github.com/OpenGeekBrains/HR_in_pocket/blob/WPFApp/src/HRInPocket/Test/AngleSharp-Console-Test/AngleSharp-Console-Test/Program.cs
> Здесь тестовый парсер открывает страницу асинхронно, Павел говорил, что асинхронности вроде стоит избегать, чтобы не словить бан.

имелось в виду не парсить hh.ru в N потоков, что бы не задетектели. Если открыть сразу 1000+ ссылок, то это будет подозрительно

**Comment by mnocard** [comment]
@Infarh сохранение в файл должно происходить автоматически при загрузке данных с сайта или при необходимости определенной командой?

**Comment by mnocard** [comment]
https://github.com/OpenGeekBrains/HR_in_pocket/pull/62

**Comment by WolfManR** [comment]
- разделить и упростить вложенные структуры кода
- разделить разные классы и интерфейсы на собственные файлы (естественно логически их распределив по каталогам)
- переписать созданный интерфейс в WPF, сделав его проще и вытащив стилизацию в отдельный файл ресурса


`namespace HRInPocket.Parsing.hh.ru.Models.Entites`
под Entity понимается сущность что будет храниться в БД
